<?php

namespace Ittybit\Types;

use Ittybit\Core\Json\JsonSerializableType;
use Ittybit\Core\Json\JsonProperty;
use Ittybit\Core\Types\ArrayType;
use DateTime;
use Ittybit\Core\Types\Date;

/**
 * Represents a processing task or a step in a workflow.
 */
class Task extends JsonSerializableType
{
    /**
     * @var string $id Unique identifier for the task.
     */
    #[JsonProperty('id')]
    public string $id;

    /**
     * @var string $object Object type, always 'task'.
     */
    #[JsonProperty('object')]
    public string $object;

    /**
     * @var mixed $kind The type of operation the task performs.
     */
    #[JsonProperty('kind')]
    public mixed $kind;

    /**
     * @var ?array<string, mixed> $input The input source for the task (e.g., details of a file). Structure varies based on the task kind and preceding steps.
     */
    #[JsonProperty('input'), ArrayType(['string' => 'mixed'])]
    public ?array $input;

    /**
     * @var ?array<string, mixed> $options Configuration options specific to the task kind.
     */
    #[JsonProperty('options'), ArrayType(['string' => 'mixed'])]
    public ?array $options;

    /**
     * @var ?array<string, mixed> $output The result generated by the task (e.g., details of an output file or intelligence data). Structure varies.
     */
    #[JsonProperty('output'), ArrayType(['string' => 'mixed'])]
    public ?array $output;

    /**
     * @var value-of<TaskStatus> $status Current status of the task.
     */
    #[JsonProperty('status')]
    public string $status;

    /**
     * @var ?int $progress Task progress percentage.
     */
    #[JsonProperty('progress')]
    public ?int $progress;

    /**
     * @var ?string $error Error message if the task failed.
     */
    #[JsonProperty('error')]
    public ?string $error;

    /**
     * @var ?string $createdBy ID of the entity that created the task (e.g., user ID, automation ID).
     */
    #[JsonProperty('created_by')]
    public ?string $createdBy;

    /**
     * @var DateTime $created Timestamp when the task was created.
     */
    #[JsonProperty('created'), Date(Date::TYPE_DATETIME)]
    public DateTime $created;

    /**
     * @var DateTime $updated Timestamp when the task was last updated.
     */
    #[JsonProperty('updated'), Date(Date::TYPE_DATETIME)]
    public DateTime $updated;

    /**
     * @var ?string $parentId ID of the parent task if this is part of a workflow.
     */
    #[JsonProperty('parent_id')]
    public ?string $parentId;

    /**
     * @var ?array<Task> $workflow Array of nested task objects representing the steps within this workflow task.
     */
    #[JsonProperty('workflow'), ArrayType([Task::class])]
    public ?array $workflow;

    /**
     * @var ?array<Task> $next Array representing subsequent tasks (e.g., in an automation). Structure may vary.
     */
    #[JsonProperty('next'), ArrayType([Task::class])]
    public ?array $next;

    /**
     * @var ?TaskResults $results
     */
    #[JsonProperty('results')]
    public ?TaskResults $results;

    /**
     * @param array{
     *   id: string,
     *   object: string,
     *   kind: mixed,
     *   status: value-of<TaskStatus>,
     *   created: DateTime,
     *   updated: DateTime,
     *   input?: ?array<string, mixed>,
     *   options?: ?array<string, mixed>,
     *   output?: ?array<string, mixed>,
     *   progress?: ?int,
     *   error?: ?string,
     *   createdBy?: ?string,
     *   parentId?: ?string,
     *   workflow?: ?array<Task>,
     *   next?: ?array<Task>,
     *   results?: ?TaskResults,
     * } $values
     */
    public function __construct(
        array $values,
    ) {
        $this->id = $values['id'];
        $this->object = $values['object'];
        $this->kind = $values['kind'];
        $this->input = $values['input'] ?? null;
        $this->options = $values['options'] ?? null;
        $this->output = $values['output'] ?? null;
        $this->status = $values['status'];
        $this->progress = $values['progress'] ?? null;
        $this->error = $values['error'] ?? null;
        $this->createdBy = $values['createdBy'] ?? null;
        $this->created = $values['created'];
        $this->updated = $values['updated'];
        $this->parentId = $values['parentId'] ?? null;
        $this->workflow = $values['workflow'] ?? null;
        $this->next = $values['next'] ?? null;
        $this->results = $values['results'] ?? null;
    }

    /**
     * @return string
     */
    public function __toString(): string
    {
        return $this->toJson();
    }
}
