name: Sync with Packagist

on:
  workflow_dispatch:
  release:
    types: [published, edited]

jobs:
  sync-packagist:
    runs-on: ubuntu-latest
    steps:
      - name: Sync with Packagist
        run: |
          # Send update request to Packagist
          curl -XPOST \
            -H 'content-type: application/json' \
            'https://packagist.org/api/update-package?username=ittybit&apiToken=${{ secrets.PACKAGIST_TOKEN }}' \
            -d '{"repository":{"url":"https://github.com/${{ github.repository }}"}}'
        

